### ISSUE TITLE
chore: Review TODO notes

### ISSUE THREAD

**Issue by madjin** [elizaOS/eliza#1223]
**Describe the bug**

See what the TODO notes are about, update their status or document as an issue if needed

- [ ] agent/src/index.ts
- [ ] packages/core/src/models.ts
- [ ] packages/core/src/runtime.ts
- [ ] packages/core/src/environment.ts
- [ ] packages/core/src/memory.ts
- [ ] packages/plugin-starknet/src/providers/trustScoreProvider.ts
- [ ] packages/plugin-starknet/src/providers/token.ts
- [ ] packages/plugin-starknet/src/actions/takeOrder.ts
- [ ] packages/plugin-starknet/src/actions/transfer.ts
- [ ] packages/plugin-starknet/readme.md
- [ ] packages/adapter-sqlite/src/sqliteTables.ts
- [ ] packages/adapter-sqljs/src/index.ts
- [ ] packages/adapter-sqljs/src/sqliteTables.ts
- [ ] packages/plugin-node/src/services/transcription.ts
- [ ] packages/plugin-node/src/services/browser.ts
- [ ] packages/client-twitter/src/search.ts
- [ ] packages/client-twitter/src/base.ts
- [ ] packages/plugin-solana/src/evaluators/trust.ts
- [ ] packages/plugin-solana/src/providers/trustScoreProvider.ts
- [ ] packages/plugin-solana/src/actions/swap.ts
- [ ] packages/plugin-solana/src/actions/takeOrder.ts
- [ ] packages/plugin-evm/src/actions/bridge.ts
- [ ] packages/plugin-evm/src/actions/swap.ts
- [ ] packages/plugin-flow/src/types/fcl.d.ts
- [ ] packages/plugin-flow/src/actions/transfer.ts
- [ ] packages/plugin-nft-generation/src/index.ts
- [ ] packages/plugin-image-generation/src/index.ts
- [ ] packages/client-farcaster/src/client.ts
- [ ] packages/adapter-supabase/src/index.ts
- [ ] packages/client-lens/src/actions.ts
- [ ] packages/client-lens/src/client.ts
- [ ] packages/client-lens/src/interactions.ts
- [ ] packages/client-discord/src/utils.ts
- [ ] packages/client-discord/src/attachments.ts
- [ ] packages/client-discord/src/messages.ts
- [ ] packages/client-discord/src/actions/chat_with_attachments.ts
- [ ] packages/client-discord/src/actions/summarize_conversation.ts
- [ ] packages/client-slack/src/events.ts

**To Reproduce**

To find the files to fix:

`grep -ro "TODO" --exclude-dir=node_modules --exclude-dir=dist | uniq` 

Some examples `grep -roP "TODO\s*.*" --exclude-dir=node_modules`
```
agent/src/index.ts:TODO: Add Slack client to the list
packages/core/dist/index.js:TODO: check
packages/core/dist/index.js:TODO: ?download=true
packages/client-discord/src/utils.ts:TODO: clean this up
packages/client-discord/src/attachments.ts:TODO: clean this up
packages/client-discord/src/messages.ts:TODO: This is throwing an error but seems to work?
packages/client-discord/src/messages.ts:TODO: Move to attachments manager
packages/client-discord/src/actions/chat_with_attachments.ts:TODO: make this dynamic and generic
packages/client-discord/src/actions/summarize_conversation.ts:TODO: parse start and end into timestamps
packages/client-slack/src/events.ts:TODO: Implement reaction handling
```

**Expected behavior**

github issue or cleaning up the code

**Screenshots**

![image](https://github.com/user-attachments/assets/ed48b42c-7701-4432-a284-5e8143f93227)

**Additional context**

**Comment by Sruthi2357** [comment]
Shall I work on this issue?
